/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_cggmp24auxinfosession_free: (a: number, b: number) => void;
export const __wbg_cggmp24signingsession_free: (a: number, b: number) => void;
export const __wbg_cggmp24thresholdkeygensession_free: (a: number, b: number) => void;
export const cggmp24EngineMetadataJson: () => [number, number, number, number];
export const cggmp24auxinfosession_advanceJson: (a: number, b: number) => [number, number, number, number];
export const cggmp24auxinfosession_drainOutgoingJson: (a: number) => [number, number, number, number];
export const cggmp24auxinfosession_new: (a: number, b: number, c: number, d: number) => [number, number, number];
export const cggmp24auxinfosession_newWithSeed: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const cggmp24auxinfosession_receiveWireMessageJson: (a: number, b: number, c: number) => [number, number, number, number];
export const cggmp24auxinfosession_resultJson: (a: number) => [number, number, number, number];
export const cggmp24auxinfosession_status: (a: number) => [number, number];
export const cggmp24signingsession_advanceJson: (a: number, b: number) => [number, number, number, number];
export const cggmp24signingsession_drainOutgoingJson: (a: number) => [number, number, number, number];
export const cggmp24signingsession_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => [number, number, number];
export const cggmp24signingsession_newWithSeed: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number) => [number, number, number];
export const cggmp24signingsession_receiveWireMessageJson: (a: number, b: number, c: number) => [number, number, number, number];
export const cggmp24signingsession_resultJson: (a: number) => [number, number, number, number];
export const cggmp24signingsession_status: (a: number) => [number, number];
export const cggmp24thresholdkeygensession_advanceJson: (a: number, b: number) => [number, number, number, number];
export const cggmp24thresholdkeygensession_drainOutgoingJson: (a: number) => [number, number, number, number];
export const cggmp24thresholdkeygensession_new: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const cggmp24thresholdkeygensession_newWithSeed: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number];
export const cggmp24thresholdkeygensession_receiveWireMessageJson: (a: number, b: number, c: number) => [number, number, number, number];
export const cggmp24thresholdkeygensession_resultJson: (a: number) => [number, number, number, number];
export const cggmp24thresholdkeygensession_status: (a: number) => [number, number];
export const combineKeyShareJson: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const coreKeySharePublicMaterialJson: (a: number, b: number) => [number, number, number, number];
export const normalizeAuxInfoPayloadJson: (a: number, b: number) => [number, number, number, number];
export const normalizeSigningPayloadJson: (a: number, b: number) => [number, number, number, number];
export const normalizeThresholdKeygenPayloadJson: (a: number, b: number) => [number, number, number, number];
export const normalizeWireMessageJson: (a: number, b: number) => [number, number, number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
